# Generated by Django 4.1.2 on 2022-11-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_diary_delete_bookdiary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="diary",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="更新日時"),
        ),
    ]
