# Generated by Django 4.1.2 on 2022-11-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0003_alter_diary_created_at_alter_diary_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="address",
            field=models.CharField(default=str, max_length=100, verbose_name="住所"),
            preserve_default=False,
        ),
    ]
