# Generated by Django 4.1.2 on 2022-11-15 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0004_diary_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
