# Generated by Django 4.1.2 on 2022-11-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0005_diary_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="lat",
            field=models.DecimalField(
                decimal_places=6, default=35.658584, max_digits=8, verbose_name="緯度"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="diary",
            name="lng",
            field=models.DecimalField(
                decimal_places=6, default=139.7454316, max_digits=9, verbose_name="経度"
            ),
            preserve_default=False,
        ),
    ]
