# Generated by Django 4.1.2 on 2022-11-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0006_diary_lat_diary_lng"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="diary",
            name="tag",
            field=models.ManyToManyField(to="diary.tag"),
        ),
    ]
